### PR TITLE
Removed DONT_CHECK in favor of CHECK_ONLY

### LINKED ISSUE #9: DONT_CHECK HaplotypeModel should be changed for eventual checks and throw error
Now `DONT_CHECK` is not checking any `Genotype` in the variant for be sure that the tool will return a correct result. Although it is an user misuse of the option, it will be nice to check from time to time if this is correct. It will speed anyway the processing, and including a random check will give more confidence that the results obtained with the tool are reliable.

Two different ways of random checking could be implemented:
- Check every _x_ variants. This is the preferred method. All the `Genotype` will be checked: if they are haploid, they pass the filter; if they have a different ploidy, both alleles should be the same. Otherwise, an `UserException` should be thrown.
- Check a random genotype in each variant. This will speed up the processing only in the case that there are tons of samples, but all the results will be reliable.

### PR DESCRIPTION
**Pull request by magicDGS**
Closes #9

### CODE REVIEW

File: src/main/java/org/magicdgs/thaplv/cmd/argumentcollections/HaplotypeModelArgumentCollection.java [hunk 1]
```diff
@@ -36,32 +36,33 @@
...
  * @author Daniel Gomez-Sanchez (magicDGS)
  */
 public abstract class HaplotypeModelArgumentCollection implements ArgumentCollectionDefinition {
     private static final long serialVersionUID = 1L;
 
-    private final boolean allowDontCheck;
+    private final boolean allowCheckOnly;
 
-    @Argument(fullName = ThaplvArgumentDefinitions.HAPLOTYPE_MODEL_LONG, shortName = ThaplvArgumentDefinitions.HAPLOTYPE_MODEL_SHORT, doc = "Haplotype model for convert calls.", common = false, optional = true)
+    @Argument(fullName = ThaplvArgumentDefinitions.HAPLOTYPE_MODEL_LONG, shortName = ThaplvArgumentDefinitions.HAPLOTYPE_MODEL_SHORT, doc = "Haplotype model for convert calls. Note that conversion tools does not accept CHECK_ONLY as model.", common = false, optional = true)
```
Comment (magicDGS) [inline src/main/java/org/magicdgs/thaplv/cmd/argumentcollections/HaplotypeModelArgumentCollection.java:48]: Probably the change here should be reflected in the javadoc documentation of the conversion program group.

Comment (magicDGS) [reply src/main/java/org/magicdgs/thaplv/cmd/argumentcollections/HaplotypeModelArgumentCollection.java:48]: Done.
